DROP DATABASE IF EXISTS hotel_test;
CREATE DATABASE hotel_test;
USE hotel_test;

CREATE TABLE habitaciones (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NUMERO VARCHAR(50),
	TIPO VARCHAR(50)
);

