DROP DATABASE IF EXISTS medicus;
CREATE DATABASE medicus;
USE medicus;

CREATE TABLE usuario (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	NOMBRE_USUARIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(40)
);

CREATE TABLE medicos (
	ID_MEDICOS INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50)
);

CREATE TABLE consultorios (
	ID_CONSULTORIOS INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NUMERO TINYINT(2)
);

CREATE TABLE pacientes ( 
	ID_PACIENTES INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	DNI INT,
	TELEFONO BIGINT
);

CREATE TABLE estados (
	ID_ESTADOS INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50)
);

CREATE TABLE turnos ( 
	ID_TURNOS INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FKMEDICO INT UNSIGNED,
	FKPACIENTE INT UNSIGNED,
	FKCONSULTORIO INT UNSIGNED,
	FKESTADO INT UNSIGNED,
	FECHA_HORA DATETIME,
	COMENTARIOS VARCHAR(500),

	FOREIGN KEY(FKMEDICO) REFERENCES medicos(ID_MEDICOS),
	FOREIGN KEY(FKPACIENTE) REFERENCES pacientes(ID_PACIENTES),
	FOREIGN KEY(FKCONSULTORIO) REFERENCES consultorios(ID_CONSULTORIOS),
	FOREIGN KEY(FKESTADO) REFERENCES estados(ID_ESTADOS)
);


INSERT INTO usuario (NOMBRE, APELLIDO, NOMBRE_USUARIO, EMAIL, PASSWORD)
VALUES 
	('Carlos', 'Martinez', 'cmartinez', 'cmartinez@medicus.com', MD5('1234'));

INSERT INTO medicos (NOMBRE, APELLIDO)
VALUES 
	('Gustavo', 'Insaurralde'),
	('Mariana', 'Rodriguez'),
	('Silvio', 'Escoltore');

INSERT INTO consultorios (NUMERO)
VALUES 
	('1'),
	('2'),
	('3'),
	('4');

INSERT INTO pacientes (NOMBRE, APELLIDO, DNI, TELEFONO)
VALUES 
	('Juan', 'Requejo',32189023, 48901237),
	('Osvaldo', 'Pitrola', 12234889, 47893126),
	('Carolina', 'Rojas', 30123890, 43451238);

INSERT INTO estados (NOMBRE) 
VALUES 
	('pendiente de confirmación'),
	('cancelado'),
	('confimado');

INSERT INTO turnos (FKMEDICO, FKPACIENTE, FKCONSULTORIO, FKESTADO, FECHA_HORA, COMENTARIOS)
VALUES 
	(1,1,1,1, '2017-10-12 09:10','comment'),
	(2,2,3,1, '2017-10-30 ','comment');



SELECT CONCAT(m.NOMBRE, ' ',m.APELLIDO) AS medico, FKPACIENTE, FKCONSULTORIO, FKESTADO, FECHA_HORA, COMENTARIOS 
FROM turnos AS t JOIN medicos AS m ON t.FKMEDICO = m.ID_MEDICOS