DROP DATABASE IF EXISTS hotel_db;
CREATE DATABASE hotel_db;
USE hotel_db;

CREATE TABLE usuarios (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	NOMBRE_USUARIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(40)
) ENGINE=InnoDB;

CREATE TABLE habitaciones( 
	ID_HABITACION INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NUMERO_HABITACION SMALLINT(4) NOT NULL,
	TIPO ENUM('matrimonial', 'single', 'double'),
	ESTADO ENUM('ocupada', 'reservada', 'libre')
) ENGINE=InnoDB;

CREATE TABLE huespedes( 
	ID_HUESPED INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50),
	EMAIL VARCHAR(100),
	TELEFONO VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE reservas( 
	ID_RESERVA INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FECHA_INICIO DATE NOT NULL,
	FECHA_SALIDA DATE NOT NULL,
	FKHABITACION INT UNSIGNED,
	FKHUESPED INT UNSIGNED,

	FOREIGN KEY (FKHABITACION) REFERENCES habitaciones(ID_HABITACION),
	FOREIGN KEY (FKHUESPED) REFERENCES huespedes(ID_HUESPED)
) ENGINE=InnoDB;


