DROP DATABASE IF EXISTS hotel_db;
CREATE DATABASE hotel_db;
USE hotel_db;

CREATE TABLE usuario (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	NOMBRE_USUARIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(40)
);

CREATE TABLE habitaciones( 
	ID_HABITACION INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NUMERO_HABITACION SMALLINT(4) NOT NULL,
	TIPO ENUM('matrimonial', 'single', 'double'),
	ESTADO ENUM('ocupada', 'reservada', 'libre')
);

CREATE TABLE huespedes( 
	ID_HUESPED INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50),
	EMAIL VARCHAR(100),
	TELEFONO INT 
);

CREATE TABLE reservas( 
	ID_RESERVA INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FECHA_INICIO DATETIME,
	FECHA_SALIDA DATETIME,
	FKHABITACION INT UNSIGNED,
	FKHUESPED INT UNSIGNED,

	FOREIGN KEY (FKHABITACION) REFERENCES habitaciones(ID_HABITACIONES),
	FOREIGN KEY (FKHUESPED) REFERENCES huespedes(ID_HUESPEDES)
);


INSERT INTO usuario (NOMBRE, APELLIDO, NOMBRE_USUARIO, EMAIL, PASSWORD)
VALUES 
	('Carlos', 'Martinez', 'cm', 'c@m.com', '1234');

INSERT INTO habitaciones (NUMERO_HABITACION, TIPO, ESTADO)
VALUES
	('101', 'matrimonial', 'libre'),
	('101', 'single', 'ocupada'),
	('101', 'double', 'reservada');

INSERT INTO huespedes (NOMBRE, APELLIDO, DIRECCION, EMAIL, TELEFONO)
VALUES
	('Carlos', 'Dacunto', NULL, NULL, NULL),
	('Analia', 'Ortiz', NULL, NULL, NULL),
	('Juan', 'Ledesma', NULL, NULL, NULL);


INSERT INTO reservas (FECHA_INICIO, FECHA_SALIDA, FKHABITACION, FKHUESPED)
VALUES
	('2017-06-10', '2017-06-24', 1, 1),
	('2017-06-10', '2017-06-24', 1, 1),
	('2017-06-10', '2017-06-24', 1, 1);